--- #YAML:1.0
name:                Business-Tax-VAT-Validation
version:             0.16
abstract:            A class for european VAT numbers validation.
license:             GPL
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    HTTP::Request::Common:         1
    LWP::UserAgent:                1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Bernard Nauwelaerts <bpn#it-development%be>
